import { generateBondConversationNarrative } from '../../core/narrative/bondConversationGeneration.ts'
import {
  bondMilestoneForEventType,
  isBondConversationEventType,
  type BondConversationMilestone,
} from '../../core/narrative/bondConversation.ts'
import type { TavernCampaignState } from '../../core/tavern/campaign/types.ts'
import type { NarrativeCandidate } from '../../core/narrative/types.ts'
import type { NarrativeProvider } from '../../ai/narrative/types.ts'
import type { UiActionResult } from '../canvas/types.ts'

export interface BondConversationGenerationDeps {
  /** Always read AFTER the `await` below, never the value captured at call
   * start — mirrors `endingNarrativeGeneration.ts`'s
   * `runEndingNarrativeGeneration` exactly (item 34). */
  campaignRef: { current: TavernCampaignState | null }
  /** Must update `campaignRef.current` and the rendered Campaign state in
   * the SAME synchronous call — `TavernSimulator`'s `commitCampaign`. */
  commitCampaign: (next: TavernCampaignState) => void
  narrativeProvider: NarrativeProvider | null
  candidateId: string
}

const MAX_PREVIOUS_BOND_CONVERSATIONS = 3

/** This Party's own previously-generated Bond Conversations, oldest-first,
 * trimmed to the most recent few (item 35/36) — derived entirely from
 * existing `campaign.narrativeCandidates`/`narrativeGenerations`, no new
 * persistent field. */
function collectPreviousBondConversations(
  campaign: TavernCampaignState,
  partyId: string,
  excludeCandidateId: string,
): { milestone: BondConversationMilestone; text: string }[] {
  const results: { milestone: BondConversationMilestone; text: string }[] = []
  const priorCandidates = campaign.narrativeCandidates
    .filter(
      (c) =>
        c.id !== excludeCandidateId &&
        c.partyId === partyId &&
        c.category === 'characterEvent' &&
        isBondConversationEventType(c.eventType) &&
        c.state === 'generated' &&
        c.activeGenerationId,
    )
    .sort((a, b) => a.dayNumber - b.dayNumber)

  for (const c of priorCandidates) {
    const milestone = bondMilestoneForEventType(c.eventType)
    const record = campaign.narrativeGenerations.find(
      (g) => g.id === c.activeGenerationId,
    )
    if (!milestone || !record) continue
    results.push({ milestone, text: record.generatedText })
  }

  return results.slice(-MAX_PREVIOUS_BOND_CONVERSATIONS)
}

/**
 * The async Bond Conversation generation flow — deliberately NOT routed
 * through `TavernSimulator.tsx`'s legacy `handleOpenExpeditionNarrative`
 * (a `setCampaign`-state-updater path), following instead the same
 * atomic-commit discipline as `runEndingNarrativeGeneration` /
 * `runMainQuestNarrativeGeneration`: read the latest Campaign via
 * `campaignRef` AFTER the `await`, and commit the outcome directly so
 * `UiActionResult` always reflects exactly what was (or was not) written.
 * A stale response — the candidate having disappeared (New Game / Loaded
 * save) or already been generated by a concurrent open — is detected and
 * handled explicitly rather than blindly overwritten.
 *
 * Returns the SAME `UiActionResult<string>` shape as the legacy
 * `handleOpenExpeditionNarrative` (item 33) so callers (DayResultsScene's
 * generic narrative-open pipeline) do not need to know which path served
 * a given candidate.
 */
export async function runBondConversationGeneration(
  deps: BondConversationGenerationDeps,
): Promise<UiActionResult<string>> {
  const { campaignRef, commitCampaign, narrativeProvider, candidateId } = deps
  const startCampaign = campaignRef.current
  if (!startCampaign) {
    return { ok: false, message: 'キャンペーンが開始されていません' }
  }

  const candidate = startCampaign.narrativeCandidates.find(
    (c) => c.id === candidateId,
  )
  if (!candidate) {
    return { ok: false, message: '物語の候補が見つかりません' }
  }

  if (candidate.state === 'generated' && candidate.activeGenerationId) {
    const record = startCampaign.narrativeGenerations.find(
      (g) => g.id === candidate.activeGenerationId,
    )
    if (record) return { ok: true, data: record.generatedText }
  }

  const milestone = bondMilestoneForEventType(candidate.eventType)
  if (!milestone || candidate.context.kind !== 'characterEvent') {
    return { ok: false, message: 'Bond Conversationの候補ではありません' }
  }
  if (!narrativeProvider) {
    return { ok: false, message: 'AI provider not connected' }
  }
  const party = startCampaign.parties.find((p) => p.id === candidate.partyId)
  if (!party) {
    return { ok: false, message: 'パーティが見つかりません' }
  }
  const focalCharacterId = candidate.context.eventFacts.focalCharacterId
  if (typeof focalCharacterId !== 'string') {
    return { ok: false, message: 'Bond Conversationの中心人物が見つかりません' }
  }

  const previousBondConversations = collectPreviousBondConversations(
    startCampaign,
    candidate.partyId,
    candidate.id,
  )

  try {
    const { record } = await generateBondConversationNarrative(
      candidate,
      party,
      milestone,
      focalCharacterId,
      candidate.dayNumber,
      previousBondConversations,
      narrativeProvider,
    )

    const latestCampaign = campaignRef.current
    if (!latestCampaign) {
      return { ok: false, message: 'キャンペーンが開始されていません' }
    }
    const latestCandidate = latestCampaign.narrativeCandidates.find(
      (c) => c.id === candidateId,
    )
    if (!latestCandidate) {
      return {
        ok: false,
        message: 'Bond Conversationの生成対象が変化したため破棄しました',
      }
    }
    if (
      latestCandidate.state === 'generated' &&
      latestCandidate.activeGenerationId
    ) {
      const existing = latestCampaign.narrativeGenerations.find(
        (g) => g.id === latestCandidate.activeGenerationId,
      )
      if (existing) return { ok: true, data: existing.generatedText }
    }

    const next: TavernCampaignState = {
      ...latestCampaign,
      narrativeCandidates: latestCampaign.narrativeCandidates.map(
        (c): NarrativeCandidate =>
          c.id === candidateId
            ? { ...c, state: 'generated', activeGenerationId: record.id }
            : c,
      ),
      narrativeGenerations: [...latestCampaign.narrativeGenerations, record],
    }
    commitCampaign(next)
    return { ok: true, data: record.generatedText }
  } catch (e) {
    const message = e instanceof Error ? e.message : '物語の生成に失敗しました'
    return { ok: false, message }
  }
}
